name = "j38-dev"
main = "src/worker.ts"
compatibility_date = "2023-07-17"
account_id = "f7b34b06da8b21a69adc4251e3e6722d"
workers_dev = false
route = { pattern = "mqtt-relay-dev.solanus.systems", zone_id="5f5587b56395030e8ceb506da91d954b", custom_domain = true }

[vars]
ENVIRONMENT = "dev"
BROKER_PUBLIC_KEYS = '''{
  "keys": [
    {
      "use": "sig",
      "kty": "OKP",
      "kid": "fT7ingBAyBkbdWlEJQfAzLuIupXJmYswTYXsZiv7OUM",
      "crv": "Ed25519",
      "alg": "EdDSA",
      "x": "3OznjIvK6uLxjaTgIsrc8s7qjpLaarNWh8gQFI3WVHc"
    },
    {
      "use": "sig",
      "kty": "OKP",
      "kid": "CRLGfgAeyG7bzareFVq3Rng00vtFq3q3gfXeNiPtmZo",
      "crv": "Ed25519",
      "alg": "EdDSA",
      "x": "6eyDt9mZY6PxIe5Vg1NrryXwyYKZQUhqH6v5ZGVUzFg"
    }
  ]
}'''

[[env.dev.analytics_engine_datasets]]
binding = "mqtt-dev"

[env.staging]
name = "j38-staging"
route = { pattern = "mqtt-relay-staging.solanus.systems", zone_id="5f5587b56395030e8ceb506da91d954b", custom_domain = true }

[env.staging.vars]
ENVIRONMENT = "staging"
BROKER_PUBLIC_KEYS = '''{
  "keys": [
    {
      "use": "sig",
      "kty": "OKP",
      "kid": "PyiBgfvTwBM4tgxvI6ETBzOwlhVTgBADsXKlb5U9Gys",
      "crv": "Ed25519",
      "alg": "EdDSA",
      "x": "i2pacM6qot7LTy_6K_yyUjFSto2Do3u1OZ2FYOXKLYA"
    },
    {
      "use": "sig",
      "kty": "OKP",
      "kid": "8-xBvOqeEnR3W1aBrox_ZakexY5ZUWqmavR72NQjwYo",
      "crv": "Ed25519",
      "alg": "EdDSA",
      "x": "KP1jnUNCQk0whaE94vPiNW4wtqyAbvPoZ6H3VsqHmA8"
    }
  ]
}'''

[[env.staging.analytics_engine_datasets]]
binding = "mqtt-staging"

[env.production]
name = "j38"
route = { pattern = "mqtt-relay.solanus.systems", zone_id="5f5587b56395030e8ceb506da91d954b", custom_domain = true }

[env.production.vars]
ENVIRONMENT = "production"
BROKER_PUBLIC_KEYS = '''{
  "keys": [
    {
      "use": "sig",
      "kty": "OKP",
      "kid": "cBuBylHNUevIZnbb54oYO-jTgwPmJIp_j5DwN6kpwk0",
      "crv": "Ed25519",
      "alg": "EdDSA",
      "x": "I4JtpfxDMjKZHpjRUhXfCT0gxoGnBG85ZPYceWh4AnY"
    },
    {
      "use": "sig",
      "kty": "OKP",
      "kid": "0AtJzorAQZ8AkiDY9bhf_-dWtSUvOcbkyAXRgNkBcn8",
      "crv": "Ed25519",
      "alg": "EdDSA",
      "x": "YwoPPv_tY_WVWjOcrSFkFIhdqp5SlFo3cmpllmH2zVg"
    }
  ]
}'''

[[env.production.analytics_engine_datasets]]
binding = "mqtt"
